### PR TITLE
Fix unauthorized error due to params order

### PR DESCRIPTION
**Pull request by irazasyed**
Took me an hour to figure why there was an unauthorized error despite having correct config. Found the bug. This is the patch for it.

### CODE REVIEW

**Comment by freekmurze** [comment]
The order was changed by @felixdorn who also tested the changes.

@felixdorn Do you know why the order of the parameters should be changed for @irazasyed 
Is this a dependency issue?

**Comment by felixdorn** [comment]
This is the constructor of the underlying object.

```
$twitterStream = new TwitterStream(
    $bearerToken = '',
    $apiKey  = '',
    $apiSecretKey = '',
);
```

I'm not exactly sure when did it change, I'm sorry for the time lost. I'm working on writing actual tests without mocking for the Twitter API.

But, yeah, this is a good catch. Can't believe I let it slip through.

**Comment by freekmurze** [comment]
Thanks!

**Comment by irazasyed** [comment]
Thanks for merging. Appreciate it.

**Pull request merged**
